// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protos/domain/jobseekerpreferences.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobseekerPreferences struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CareerLevelId   int32             `protobuf:"varint,2,opt,name=career_level_id,json=careerLevelId,proto3" json:"career_level_id,omitempty"`
	CareerLevel     string            `protobuf:"bytes,3,opt,name=career_level,json=careerLevel,proto3" json:"career_level,omitempty"`
	AvailabilityId  int32             `protobuf:"varint,4,opt,name=availability_id,json=availabilityId,proto3" json:"availability_id,omitempty"`
	Availability    string            `protobuf:"bytes,5,opt,name=availability,proto3" json:"availability,omitempty"`
	EmploymentTypes []*EmploymentType `protobuf:"bytes,6,rep,name=employment_types,json=employmentTypes,proto3" json:"employment_types,omitempty"`
}

func (x *JobseekerPreferences) Reset() {
	*x = JobseekerPreferences{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_domain_jobseekerpreferences_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobseekerPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobseekerPreferences) ProtoMessage() {}

func (x *JobseekerPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_protos_domain_jobseekerpreferences_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobseekerPreferences.ProtoReflect.Descriptor instead.
func (*JobseekerPreferences) Descriptor() ([]byte, []int) {
	return file_protos_domain_jobseekerpreferences_proto_rawDescGZIP(), []int{0}
}

func (x *JobseekerPreferences) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobseekerPreferences) GetCareerLevelId() int32 {
	if x != nil {
		return x.CareerLevelId
	}
	return 0
}

func (x *JobseekerPreferences) GetCareerLevel() string {
	if x != nil {
		return x.CareerLevel
	}
	return ""
}

func (x *JobseekerPreferences) GetAvailabilityId() int32 {
	if x != nil {
		return x.AvailabilityId
	}
	return 0
}

func (x *JobseekerPreferences) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

func (x *JobseekerPreferences) GetEmploymentTypes() []*EmploymentType {
	if x != nil {
		return x.EmploymentTypes
	}
	return nil
}

var File_protos_domain_jobseekerpreferences_proto protoreflect.FileDescriptor

var file_protos_domain_jobseekerpreferences_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88,
	0x02, 0x0a, 0x14, 0x4a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x61, 0x72, 0x65, 0x65,
	0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12,
	0x48, 0x0a, 0x10, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6d,
	0x71, 0x2d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_domain_jobseekerpreferences_proto_rawDescOnce sync.Once
	file_protos_domain_jobseekerpreferences_proto_rawDescData = file_protos_domain_jobseekerpreferences_proto_rawDesc
)

func file_protos_domain_jobseekerpreferences_proto_rawDescGZIP() []byte {
	file_protos_domain_jobseekerpreferences_proto_rawDescOnce.Do(func() {
		file_protos_domain_jobseekerpreferences_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_domain_jobseekerpreferences_proto_rawDescData)
	})
	return file_protos_domain_jobseekerpreferences_proto_rawDescData
}

var file_protos_domain_jobseekerpreferences_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_domain_jobseekerpreferences_proto_goTypes = []interface{}{
	(*JobseekerPreferences)(nil), // 0: protos.domain.JobseekerPreferences
	(*EmploymentType)(nil),       // 1: protos.domain.EmploymentType
}
var file_protos_domain_jobseekerpreferences_proto_depIdxs = []int32{
	1, // 0: protos.domain.JobseekerPreferences.employment_types:type_name -> protos.domain.EmploymentType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_domain_jobseekerpreferences_proto_init() }
func file_protos_domain_jobseekerpreferences_proto_init() {
	if File_protos_domain_jobseekerpreferences_proto != nil {
		return
	}
	file_protos_domain_employment_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_domain_jobseekerpreferences_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobseekerPreferences); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_domain_jobseekerpreferences_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_domain_jobseekerpreferences_proto_goTypes,
		DependencyIndexes: file_protos_domain_jobseekerpreferences_proto_depIdxs,
		MessageInfos:      file_protos_domain_jobseekerpreferences_proto_msgTypes,
	}.Build()
	File_protos_domain_jobseekerpreferences_proto = out.File
	file_protos_domain_jobseekerpreferences_proto_rawDesc = nil
	file_protos_domain_jobseekerpreferences_proto_goTypes = nil
	file_protos_domain_jobseekerpreferences_proto_depIdxs = nil
}
