// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protos/service/employer-service.proto

package service

import (
	domain "github.com/wanpng/mq-producer-service/grpc/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendToMQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employer *domain.Employer `protobuf:"bytes,1,opt,name=employer,proto3" json:"employer,omitempty"`
	Error    *domain.Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SendToMQResponse) Reset() {
	*x = SendToMQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_employer_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToMQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToMQResponse) ProtoMessage() {}

func (x *SendToMQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_employer_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToMQResponse.ProtoReflect.Descriptor instead.
func (*SendToMQResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_employer_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendToMQResponse) GetEmployer() *domain.Employer {
	if x != nil {
		return x.Employer
	}
	return nil
}

func (x *SendToMQResponse) GetError() *domain.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_protos_service_employer_service_proto protoreflect.FileDescriptor

var file_protos_service_employer_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x10, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x4d, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x72, 0x52, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x32, 0x50, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x72, 0x4d, 0x51, 0x12, 0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x4d, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6d, 0x71, 0x2d, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_service_employer_service_proto_rawDescOnce sync.Once
	file_protos_service_employer_service_proto_rawDescData = file_protos_service_employer_service_proto_rawDesc
)

func file_protos_service_employer_service_proto_rawDescGZIP() []byte {
	file_protos_service_employer_service_proto_rawDescOnce.Do(func() {
		file_protos_service_employer_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_service_employer_service_proto_rawDescData)
	})
	return file_protos_service_employer_service_proto_rawDescData
}

var file_protos_service_employer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_service_employer_service_proto_goTypes = []interface{}{
	(*SendToMQResponse)(nil), // 0: service.SendToMQResponse
	(*domain.Employer)(nil),  // 1: domain.Employer
	(*domain.Error)(nil),     // 2: domain.Error
}
var file_protos_service_employer_service_proto_depIdxs = []int32{
	1, // 0: service.SendToMQResponse.employer:type_name -> domain.Employer
	2, // 1: service.SendToMQResponse.error:type_name -> domain.Error
	1, // 2: service.EmployerService.sendEmployerMQ:input_type -> domain.Employer
	0, // 3: service.EmployerService.sendEmployerMQ:output_type -> service.SendToMQResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_service_employer_service_proto_init() }
func file_protos_service_employer_service_proto_init() {
	if File_protos_service_employer_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_service_employer_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToMQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_service_employer_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_employer_service_proto_goTypes,
		DependencyIndexes: file_protos_service_employer_service_proto_depIdxs,
		MessageInfos:      file_protos_service_employer_service_proto_msgTypes,
	}.Build()
	File_protos_service_employer_service_proto = out.File
	file_protos_service_employer_service_proto_rawDesc = nil
	file_protos_service_employer_service_proto_goTypes = nil
	file_protos_service_employer_service_proto_depIdxs = nil
}
