// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	domain "github.com/wanpng/mq-producer-service/grpc/domain"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// EmployerServiceClient is the client API for EmployerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployerServiceClient interface {
	SendEmployerMQ(ctx context.Context, in *domain.Employer, opts ...grpc.CallOption) (*SendToMQResponse, error)
}

type employerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployerServiceClient(cc grpc.ClientConnInterface) EmployerServiceClient {
	return &employerServiceClient{cc}
}

func (c *employerServiceClient) SendEmployerMQ(ctx context.Context, in *domain.Employer, opts ...grpc.CallOption) (*SendToMQResponse, error) {
	out := new(SendToMQResponse)
	err := c.cc.Invoke(ctx, "/service.EmployerService/sendEmployerMQ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployerServiceServer is the server API for EmployerService service.
// All implementations must embed UnimplementedEmployerServiceServer
// for forward compatibility
type EmployerServiceServer interface {
	SendEmployerMQ(context.Context, *domain.Employer) (*SendToMQResponse, error)
	mustEmbedUnimplementedEmployerServiceServer()
}

// UnimplementedEmployerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmployerServiceServer struct {
}

func (UnimplementedEmployerServiceServer) SendEmployerMQ(context.Context, *domain.Employer) (*SendToMQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmployerMQ not implemented")
}
func (UnimplementedEmployerServiceServer) mustEmbedUnimplementedEmployerServiceServer() {}

// UnsafeEmployerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployerServiceServer will
// result in compilation errors.
type UnsafeEmployerServiceServer interface {
	mustEmbedUnimplementedEmployerServiceServer()
}

func RegisterEmployerServiceServer(s grpc.ServiceRegistrar, srv EmployerServiceServer) {
	s.RegisterService(&_EmployerService_serviceDesc, srv)
}

func _EmployerService_SendEmployerMQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.Employer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployerServiceServer).SendEmployerMQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.EmployerService/sendEmployerMQ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployerServiceServer).SendEmployerMQ(ctx, req.(*domain.Employer))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.EmployerService",
	HandlerType: (*EmployerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendEmployerMQ",
			Handler:    _EmployerService_SendEmployerMQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/service/employer-service.proto",
}
